server:
  port: 0

spring:
  application:
    name: source_stream
  cloud:
    stream:
      bindings:
        output:
          destination: demo-source
          contentType: application/*+avro
      kafka:
        brokers: localhost:9092
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
      schemaRegistryClient:
        endpoint: http://localhost:8111
        cached: true
