server:
  port: 0

spring:
  application:
    name: sink_stream
  cloud:
    stream:
      bindings:
        input:
          destination: demo-sink
          group: sink-group
      kafka:
        brokers: localhost
        defaultBrokerPort: 9092
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
      schemaRegistryClient:
        endpoint: http://localhost:8111
        cached: true